### ISSUE TITLE
Auth0 Integration Breaks with Turbopack And App Router

### ISSUE THREAD

**Issue by faran-tenovos** [auth0/nextjs-auth0#1412]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When integrating Auth0 with a Next.js application that uses Turbopack and App Router, an error occurs during rendering. The error message displayed is: `error rendering: TypeError: _react.default.createContext is not a function.` While If I do not use turbo-pack it works fine.
Here is the debug info when using turbpack for reference

```
- error rendering: TypeError: _react.default.createContext is not a function
      at Object. (node_modules/.pnpm/next@13.4.19_@babel+core@7.22.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/app-router-context.js:45:41) [/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:2182:41]
      [at [project]/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/app-router-context.js (ecmascript, ssr) (/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:2193:3)]
      at /turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:322:21 [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:394:27]
      at runModuleExecutionHooks (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:374:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:427:9]
      at instantiateModule (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:321:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:393:9]
      at getOrInstantiateModuleFromParent (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:422:10) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:454:12]
      at commonJsRequire (/turbopack/[turbopack]/shared/runtime-utils.ts:219:18) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:109:20]
      at Object. (node_modules/.pnpm/next@13.4.19_@babel+core@7.22.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/navigation.js:61:27) [/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:2255:27]
      [at [project]/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/navigation.js (ecmascript, ssr) (/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:2393:3)]
      at /turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:322:21 [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:394:27]
      at runModuleExecutionHooks (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:374:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:427:9]
      at instantiateModule (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:321:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:393:9]
      at getOrInstantiateModuleFromParent (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:422:10) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:454:12]
      at commonJsRequire (/turbopack/[turbopack]/shared/runtime-utils.ts:219:18) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:109:20]
      at Object. (node_modules/.pnpm/next@13.4.19_@babel+core@7.22.10_react-dom@18.2.0_react@18.2.0/node_modules/next/navigation.js:1:18) [/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:2396:18]
      [at [project]/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.10_react-dom@18.2.0_react@18.2.0/node_modules/next/navigation.js (ecmascript, ssr) (/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:2398:3)]
      at /turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:322:21 [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:394:27]
      at runModuleExecutionHooks (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:374:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:427:9]
      at instantiateModule (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:321:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:393:9]
      at getOrInstantiateModuleFromParent (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:422:10) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:454:12]
      at commonJsRequire (/turbopack/[turbopack]/shared/runtime-utils.ts:219:18) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:109:20]
      at Object. (node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/helpers/with-page-auth-required.js:3:22) [/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:64337:22]
      [at [project]/node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/helpers/with-page-auth-required.js (ecmascript, ssr) (/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:64394:3)]
      at /turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:322:21 [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:394:27]
      at runModuleExecutionHooks (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:374:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:427:9]
      at instantiateModule (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:321:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:393:9]
      at getOrInstantiateModuleFromParent (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:422:10) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:454:12]
      at commonJsRequire (/turbopack/[turbopack]/shared/runtime-utils.ts:219:18) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:109:20]
      at Object. (node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/helpers/index.js:9:33) [/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:64473:33]
      [at [project]/node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/helpers/index.js (ecmascript, ssr) (/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:64481:3)]
      at /turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:322:21 [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:394:27]
      at runModuleExecutionHooks (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:374:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:427:9]
      at instantiateModule (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:321:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:393:9]
      at getOrInstantiateModuleFromParent (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:422:10) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:454:12]
      at commonJsRequire (/turbopack/[turbopack]/shared/runtime-utils.ts:219:18) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:109:20]
      at Object. (node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/init.js:8:19) [/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:65163:19]
      [at [project]/node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/init.js (ecmascript, ssr) (/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:65207:3)]
      at /turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:322:21 [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:394:27]
      at runModuleExecutionHooks (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:374:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:427:9]
      at instantiateModule (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:321:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:393:9]
      at getOrInstantiateModuleFromParent (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:422:10) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:454:12]
      at commonJsRequire (/turbopack/[turbopack]/shared/runtime-utils.ts:219:18) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:109:20]
      at Object. (node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/index.js:7:16) [/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:65218:16]
      [at [project]/node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/index.js (ecmascript, ssr) (/some-user/.next/server/app/chunks/ssr/node_modules_263d78._.js:65280:3)]
      at /turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:322:21 [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:394:27]
      at runModuleExecutionHooks (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:374:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:427:9]
      at instantiateModule (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:321:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:393:9]
      at getOrInstantiateModuleFromParent (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:422:10) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:454:12]
      at esmImport (/turbopack/[turbopack]/shared/runtime-utils.ts:203:18) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:102:20]
      [at /some-user/.next/server/app/chunks/ssr/src_app_api_auth_[auth0]_route_ts_fe5a7a._.js:8:236]
      [at [project]/src/app/api/auth/[auth0]/route.ts (ecmascript, ssr) (/some-user/.next/server/app/chunks/ssr/src_app_api_auth_[auth0]_route_ts_fe5a7a._.js:13:3)]
      at /turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:322:21 [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:394:27]
      at runModuleExecutionHooks (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:374:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:427:9]
      at instantiateModule (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:321:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:393:9]
      at getOrInstantiateModuleFromParent (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:422:10) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:454:12]
      at esmImport (/turbopack/[turbopack]/shared/runtime-utils.ts:203:18) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:102:20]
      [at /some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_9535cc._.js:8:131]
      [at [next]/entry/app/route.ts/(ENTRY)/[project]/src/app/api/auth/[auth0]/route.ts (ecmascript)/(BOOTSTRAP_CONFIG)/[project]/src/app/api/auth/[auth0]/route.ts/bootstrap-config.ts (ecmascript) (ecmascript, ssr) (/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_9535cc._.js:30:3)]
      at /turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:322:21 [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:394:27]
      at runModuleExecutionHooks (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:374:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:427:9]
      at instantiateModule (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:321:5) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:393:9]
      at getOrInstantiateRuntimeModule (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:1280:10) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:1000:12]
      at Object.registerChunk (/turbopack/[turbopack]/dev/runtime/nodejs/runtime-backend-nodejs.ts:85:11) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:1141:21]
      at registerChunk (/turbopack/[turbopack]/dev/runtime/base/runtime-base.ts:1341:18) [/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:1040:20]
      [at ]
      [at /some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:1165:18]
      [at Object. (/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_f3a4eb._.js:1166:3)]
      [at Module._compile (node:internal/modules/cjs/loader:1233:14)]
      [at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)]
      [at Module.load (node:internal/modules/cjs/loader:1091:32)]
      [at Module._load (node:internal/modules/cjs/loader:938:12)]
      [at Module.require (node:internal/modules/cjs/loader:1115:19)]
      [at require (node:internal/modules/helpers:130:18)]
      [at Object. (/some-user/.next/server/app/chunks/ssr/[next]_entry_app_route_ts_5edc83._.js:13:1)]
      [at Module._compile (node:internal/modules/cjs/loader:1233:14)]
      [at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)]
      [at Module.load (node:internal/modules/cjs/loader:1091:32)]
      [at Module._load (node:internal/modules/cjs/loader:938:12)]
      [at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)]
      [at node:internal/main/run_main_module:23:47]

status: exit status: 0
```

### Reproduction

1. Set up a Next.js application.
2. Use Turbopack with App Router
3. Implement Auth0 authentication.
4. Navigate to an auth route such `/api/auth/login`.
5. Observe the error message.

### nextjs-auth0 version

3.1.0

### Next.js version

13.4.19

### Node.js version

20.5.1 & 18.17.1

**Comment by adamjmcgrath** [comment]
Hi @faran-tenovos - thanks for raising this

I can't replace your issue on the sample app, using `next dev --turbo` appears to work correctly.

This error usually means you're trying to run client side code (eg `@auth0/nextjs-auth0/client`) in a server component. If you can share a repro that demonstrates the issue, I can debug it for you.

**Comment by faran-tenovos** [comment]
@adamjmcgrath https://github.com/faran-tenovos/auth0-turbopack-approuter-issue Here is the repo I've pushed it. You can see if you use `next dev --turbo` it breaks while without `--turbo it works fine.`

**Comment by adamjmcgrath** [comment]
Thanks for sharing the repo @faran-tenovos 

The issue appears to be coming from using `next/navigation`, I've removed this SDK from your example and replaced the api route with:

```js
import { redirect } from 'next/navigation';

export const GET = () => {
    redirect('/');
}
```

See https://github.com/faran-tenovos/auth0-turbopack-approuter-issue/compare/main...adamjmcgrath:auth0-turbopack-approuter-issue:main

And I still get the same error. I also notice you get a different error when you try and use it in a page (which is reported here https://github.com/vercel/next.js/issues/52227)

Turbopack is [still in beta](https://nextjs.org/docs/architecture/turbopack#:~:text=Turbopack-,(beta),-is%20an%20incremental) - so I suspect they still have a few issues to iron out. You should raise this in the Next or turbopack repos
