### ISSUE TITLE
"failed to validate JWT signature"

### ISSUE THREAD

**Issue by powderham** [auth0/nextjs-auth0#21]
### Description

When the user is returned to my callback url `api/auth/callback`, I receive the error:

```
RPError: failed to validate JWT signature
```

My setup is incredibly basic, so can't seem to find anything idiosyncratic in my app that would be causing the issue - although this is my first time working with auth0, so it could be a simple config issue.

When checking auth0, I can see the user login/signup is registered, just the `handleCallback` method fails with the above error.

my callback url at `/api/auth/callback.ts`:

```
import auth0 from "../../../utils/auth0";
import { NextApiRequest, NextApiResponse } from "next";

export default async function callback(
  req: NextApiRequest,
  res: NextApiResponse
) {
  try {
    console.log(res, req);
    await auth0.handleCallback(req, res, { redirectTo: "/" });
  } catch (error) {
    console.error(error);
    res.status(error.status || 400).end(error.message);
  }
}
```

my login url at : `api/auth/login.ts`:

```
import auth0 from "../../../utils/auth0";
import { NextApiRequest, NextApiResponse } from "next";

export default async function login(req: NextApiRequest, res: NextApiResponse) {
  try {
    await auth0.handleLogin(req, res);
  } catch (error) {
    console.error(error);
    res.status(error.status || 400).end(error.message);
  }
}
```

My initAuth0: 

```
import { initAuth0 } from "@auth0/nextjs-auth0";

export default initAuth0({
  domain: [removed],
  clientId: [removed],
  clientSecret:
   [removed],
  scope: "openid profile",
  redirectUri: "http://localhost:3000/api/auth/callback",
  postLogoutRedirectUri: "http://localhost:3000/",
  session: {
    // The secret used to encrypt the cookie.
    cookieSecret: [removed - i just added a 32 char random string here],
    // The cookie lifetime (expiration) in seconds. Set to 8 hours by default.
    cookieLifetime: 60 * 60 * 8,
    // Store the id_token in the session. Defaults to false.
    storeIdToken: false,
    // Store the access_token in the session. Defaults to false.
    storeAccessToken: false,
    // Store the refresh_token in the session. Defaults to false.
    storeRefreshToken: false
  },
  oidcClient: {
    // Optionally configure the timeout in milliseconds for HTTP requests to Auth0.
    httpTimeout: 2500,
    // Optionally configure the clock tolerance in milliseconds, if the time on your server is running behind.
    clockTolerance: 10000
  }
});
```

My setup in `auth0`

![image](https://user-images.githubusercontent.com/18611511/66646948-e3214980-ec27-11e9-888b-0dbe176e6af9.png)

**Comment by sandrinodimattia** [comment]
@powderham could you verify that the domain and clientId exactly matches what you see in the dashboard?

**Comment by Afsoon** [comment]
After a couple hours unable to login because the algorithm is invalid, go to your App configuration, on Auth0, and show advanced setting and changes de algorithm from `HS256` to `RS256`, I just found that HS256 was the default algorithm. I don't know if it can help you, but I didn't found you have to change this in any tutorial.

![imagen](https://user-images.githubusercontent.com/713534/67221913-c5b86080-f41b-11e9-96b8-21fc6691389f.png)

**Comment by powderham** [comment]
@Afsoon thanks for getting back to me.

Mine was originally set to `RS256`, I changed it to `HS256` just to double check and got `unexpected JWT alg received, expected RS256, got: HS256` so I don't think it's the _only_ setting required.

Are you able to send me additional screenshots of your (advanced) settings so I can cross reference?

**Comment by charltoons** [comment]
@powderham What node version are you using? I ran into the same issue when trying to use `node@11.x.x`, but was able to get it working with `node@12.12.0`. It appears that some of the Auth0 lib's dependencies (namely `openid-client`) are incompatible with node v11 and issue the following warning during `npm install`:

```
Unsupported engine for openid-client@3.7.3: wanted: {"node":"^10.13.0 || >=12.0.0"} (current: {"node":"11.14.0","npm":"6.12.0"})
```

**Comment by Afsoon** [comment]
@powderham The rest of my advanced settings are values by default, I didn't change anything. I think can be a good idea to take a look up in your node version because in my case I have `node v12.4.0`

**Comment by sandrinodimattia** [comment]
For those of you that bumped into issue, can you confirm the following:

- The application is a Regular Web Application
- **Json Web Token Signature Algorithm** is set to RS256 (under Advanced Settings, OAuth)
- **OIDC Conformant** is set to True (under Advanced Settings, OAuth)
- You're running Node 10.13 or Node 12

**Comment by Afsoon** [comment]
Sorry for my late answer. Yes, I have a regular web application, with RS256 and OIDC Conformant and using node 12.

**Comment by Miz85** [comment]
Hi 👋 I'm running into this exact issue and I can confirm I can answer yes to all @sandrinodimattia's questions except my app was created as "single page app" in auth0 and i'm running node v12.10.0.

**Comment by powderham** [comment]
- [x]   The application is a Regular Web Application
- [x]  Json Web Token Signature Algorithm is set to RS256 (under Advanced Settings, OAuth)
- [x]   OIDC Conformant is set to True (under Advanced Settings, OAuth)
- [x]   You're running Node 10.13 or Node 12 

Chaps, apologies for the delay. Today I tried again and fixed my node version to `v12.12.0` as per @charltoons and it worked.
I tried also with `x12.4.0` as per @Afsoon which also worked.

Unfortunately I can't put my finger on exactly what it was, but I believe the node version played a factor.

@Miz85 - if I can use 12.4.0 and 12.12.0 without problem, then perhaps the problem is the single page app.

@sandrinodimattia from my perspective my issue is solved, happy to close, feel free to keep open to get to the bottom of the issue.

**Comment by BjoernRave** [comment]
For me this error persists. I have no idea what to do about it really.

I triple checked all the points mentioned above. I am using `nvm` with `nvm use 12.12.0` to set the right node version. I have the algorithm set to `RS256` and `OICD` turned on. 

The weird thing is that on my backend I am actually able to authenticate the request with the accessToken and can console.log the scope and permissions, but on my client side I keep getting the same result: 

```
[CombinedError: [Network] undefined] {
  name: 'CombinedError',
  message: '[Network] undefined',
  graphQLErrors: [
    GraphQLError: invalid algorithm
        at rehydrateGraphQlError (/Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/index-dddbd19e.js:23:12)
        at Array.map (<anonymous>)
        at new CombinedError (/Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/index-dddbd19e.js:39:61)
        at /Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/core.js:524:30
        at _ref3 (/Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/core.js:531:6)
        at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:759:56
        at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:748:28
        at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:865:14)
        at Array.forEach (<anonymous>)
        at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:864:77)
        at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:492:42
        at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:760:16
        at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:748:28
        at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:865:14)
        at Array.forEach (<anonymous>)
        at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:864:77) {
      message: 'invalid algorithm'
    }
  ],
  networkError: Error: undefined
      at /Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/core.js:525:25
      at _ref3 (/Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/core.js:531:6)
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:759:56
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:748:28
      at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:865:14)
      at Array.forEach (<anonymous>)
      at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:864:77)
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:492:42
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:760:16
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:748:28
      at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:865:14)
      at Array.forEach (<anonymous>)
      at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:864:77)
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:760:16
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:748:28
      at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:865:14),
  response: undefined
}
```

**Comment by Afsoon** [comment]
@BjoernRave can you create a minimal project or link to repository to check the code?. Because this way I can't know why is the problem.

**Comment by BjoernRave** [comment]
@Afsoon okay, I created a minimal project: https://github.com/BjoernRave/Auth0-Urql-Nextjs-Prisma2

**Comment by Afsoon** [comment]
Hello @BjoernRave ,sorry for my late response I was a bit busy theses days,  after check you repository I found your problem. The configuration is almost correct, you have the same misunderstood that I had with `accessToken`, If I am not wrong, the `accessToken` is a value to interact with Auth0 API not external resources. Due that `accessToken` is not a JWT, you API is always complaining for the same reason, `invalid algorithm`.

In your Auth0 configuration you must set `storeIdToken` to `true` and each time you call `getSession` you must look for the property `idToken`, this property is the JWT that you are looking.

**Comment by BjoernRave** [comment]
@Afsoon first off, thanks for trying to help me :)

Are you sure that the idToken is the only way to authenticate my request, because the accessToken is also a JWT in my case and my backend is also able to verify and decode it. 

Referring to stuff from here: https://auth0.com/docs/tokens

When using the idToken my backend is also able to verify and decode it, but I still get the `invalid algorithm` error.

At first I got: `jwt audience invalid. expected: `, but then I changed the audience on my server to the client ID of my frontend application.

Also just to clarify on Auth0 I have two applications, one being my frontend service and one my backend service. Then I have one API (beside the management API), which is also my backend application.

I can also only reach the login page on the frontend if I pass the identifier of my Backend API as audience.

**Comment by Afsoon** [comment]
About the access token, I'm sure, as you can find the documentation that you listed, the access token isn't always an JWT, it can't tell you if an user is authenticated and it is use to grant permission for an application. 

If you are still having the same error, check the configuration if your library it's using the same algorithm to decode the JWT as Auth0.

If you are using another backend application and Auth0, unless you need verify the signature of the JWT you must share the public key of Auth0 with you backend application.

**Comment by BjoernRave** [comment]
but if I am using RS256 (which I am), I think the accessToken is always a JWT. Also looking at the example provided in the repo: https://github.com/auth0/nextjs-auth0/tree/master/examples/api-call-example they are also only using the accessToken.
