### ISSUE TITLE
Flag to use env only at runtime

### ISSUE THREAD

**Issue by francescovenica** [auth0/nextjs-auth0#376]
### Describe the problem you'd like to have solved

I want to create a docker image without expose secrets in the image.

### Describe the ideal solution

Have a flag to avoid using env variables during the build process keeping in mind that some function could not work (ex. [static generation](https://nextjs.org/docs/basic-features/pages#static-generation-recommended))

## Alternatives and current work-arounds

N/A

**Comment by adamjmcgrath** [comment]
Hi @francescovenica - you don't need the env vars at build time

How are you configuring the SDK and what errors are you getting on you docker image when you leave the env vars out?

**Comment by francescovenica** [comment]
This is how I'm configuring the SDK:

```
import { initAuth0 } from "@auth0/nextjs-auth0";

export default initAuth0({
  baseURL: process.env.NEXT_PUBLIC_BASE_URL,
  secret: process.env.AUTH0_SECRET,
  issuerBaseURL: process.env.AUTH0_ISSUER_BASE_URL,
  clientID: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET
});
```

and this is the error I get on build time:
```
TypeError: "secret" is required,
at Object.get (.......node_modules/@auth0/nextjs-auth0/dist/auth0-session/get-config.js:145:15)
```

**Comment by adamjmcgrath** [comment]
Hi @francescovenica 

You don't need to run `initAuth` - you can just create the env vars and use the named exports directly (see https://auth0.github.io/nextjs-auth0/modules/config.html#1-environmental-variables)

If you do want to construct your own instance, see https://github.com/auth0/nextjs-auth0/issues/154#issuecomment-677458794 for how to do this in a way that wont initialise at build time

**Comment by francescovenica** [comment]
I've tried using:
```
let auth0;
export default () => {
  if (!auth0) {
    auth0 = initAuth0({
      baseURL: process.env.NEXT_PUBLIC_BASE_URL,
      secret: process.env.AUTH0_SECRET,
      issuerBaseURL: process.env.AUTH0_ISSUER_BASE_URL,
      clientID: process.env.AUTH0_CLIENT_ID,
      clientSecret: process.env.AUTH0_CLIENT_SECRET
    });
  }
  return auth0;
};

```

but I'm still getting the error, on server side everything is imported using this file and used in this way: `auth0().getXXXX` while for client side I'm importing from the module.

**Comment by francescovenica** [comment]
I think I fount the issue, using getSession in `_app.tsx` thrown the error, if I remove it I 'm able to build without any env

**Comment by adamjmcgrath** [comment]
@francescovenica - can you share your code for `_app.tsx`?

**Comment by francescovenica** [comment]
This is the initialProps function:

```
const initialProps = async ({ ctx, Component }) => {
  const { req, res, pathname } = ctx;

  // Let's api work normally
  if (pathname.indexOf("/api") !== -1) { return {}; }

  const session = await auth0.getSession(req, res);
  if (session) {
    const { user } = session;
    if (user.foo) {
      if (res) {
        res.writeHead(302, { Location: "/foo" });
        res.end();
      } else {
        Router.replace("/foo");
      }
      return {};
    }
  }

  if (Component.getServerSideProps) {
    Object.assign({}, await Component.getServerSideProps(ctx));
  }

  return {};
};
```

while the app is very simple:
```

const App = ({ Component, pageProps, ...rest }: AppProps) => {
  const apolloClient = useApollo(pageProps?.initialApolloState);

  const { error } = useApi("/profile");
  if (error?.status === 401) {
    window.location.assign(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/auth/logout`
    );
  }

  return (
    <ApolloProvider client={apolloClient}>
      <Component {...pageProps} apolloClient={apolloClient} {...rest} />
    </ApolloProvider>
  );
};

const AuthApp = ({ Component, pageProps, ...rest }: AppProps) => {
  return (
    <UserProvider>
      <App Component={Component} pageProps={pageProps} {...rest} />
    </UserProvider>
  );
};

export default appWithTranslation(AuthApp);
```

**Comment by adamjmcgrath** [comment]
> const session = await auth0.getSession(req, res);

If your `auth0` instance looks like https://github.com/auth0/nextjs-auth0/issues/376#issuecomment-825052748 then this line should be more like `auth0().getSession(req, res)`

Also, since `getInitialProps` runs in the build, you should check that a request exists before you instantiate auth0, eg

```js
if (req) {
  const session = await auth0.getSession(req, res);
}
```

**Comment by adamjmcgrath** [comment]
Also, see https://nextjs.org/docs/api-reference/data-fetching/getInitialProps#caveats wrt using server-side modules inside `getInitialProps`

**Comment by tusbar** [comment]
@adamjmcgrath 

> If you do want to construct your own instance, see [#154 (comment)](https://github.com/auth0/nextjs-auth0/issues/154#issuecomment-677458794) for how to do this in a way that wont initialise at build time

This doesn’t work for `withPageAuthRequired` as it will be called at build time.

There’s a workaround for the global instance: https://github.com/auth0/nextjs-auth0/blob/main/src/index.ts#L102-L103
But `withPageAuthRequiredFactory` is not exposed, so there’s no real way to implement this on your own auth0 instance.

**Comment by adamjmcgrath** [comment]
Hi @tusbar - thanks for your contribution. Could you share the code you are using that is failing at build time and what the error is?

**Comment by francescovenica** [comment]
@adamjmcgrath I have a question still on this subject, if I create a custom instance can I use the getSession imported from the default package? I need to get secrets from gcp so I need to init auth0 with a promise but I'm also using apollo client and I'm injecting the access_token in the headers when I create the apollo client, in this case I can't return a promise as apollo client need to be sync...

**Comment by adamjmcgrath** [comment]
Hi @francescovenica - thanks for your question

> if I create a custom instance can I use the getSession imported from the default package

No, the 2 can't be used interchangeably

**Comment by tusbar** [comment]
@adamjmcgrath 

> Hi @tusbar - thanks for your contribution. Could you share the code you are using that is failing at build time and what the error is?

Let’s say that you have something like this in `lib/auth0.js`:

```js
import {initAuth0} from '@auth0/nextjs-auth0'

// Since Vercel removed the ability to map system env variables, we have implemented a custom getBaseUrl that uses process.env.VERCEL_ENV.
function getBaseUrl() {
  const baseUrl = process.env.AUTH0_BASE_URL ?? process.env.VERCEL_URL

  if (!baseUrl) {
    return 'http://localhost:4000'
  }

  if (!/^https?:\/\//.test(baseUrl)) {
    return `https://${baseUrl}`
  }

  return baseUrl
}

function getInstance() {
  if (instance) {
    return instance
  }

  instance = initAuth0({
    baseURL: getBaseUrl()
  })

  return instance
}

export const getSession = (...args) => getInstance().getSession(...args)
export const getAccessToken = (...args) => getInstance().getAccessToken(...args)
// ... other exported auth0 functions
// This one causes the issue:
export const withPageAuthRequired = (...args) => getInstance().withPageAuthRequired(...args)
```

Then in a page, you’re doing the following:

```js
import {withPageAuthRequired} from '../lib/auth0'

export default function Page({foo}) {
  return (
    <div>{foo}</div>
  )
}

export const getServerSideProps = withPageAuthRequired({
  getServerSideProps: () => ({
    props: {foo: 'bar'}
  })
})
```

Here, `withPageAuthRequired` will be called when the page is built, which will cause `getInstance` to be called, which will call `initAuth0`, which will fail.

I have fixed the issue by implementing a custom `withPageAuthRequiredFactory` (based on [the one in this repository](https://github.com/auth0/nextjs-auth0/blob/main/src/helpers/with-page-auth-required.ts#L93)), which looks something like this:

```js
function withPageAuthRequiredFactory() {
  const loginUrl = process.env.NEXT_PUBLIC_AUTH0_LOGIN || '/api/auth/login'

  return (options = {}) => {
    if (typeof options === 'function') {
      throw new TypeError('Unsupported usage of withPageAuthRequired, don’t wrap your component, but use it as a getServerSideProps wrapper')
    }

    const {getServerSideProps, returnTo} = options

    return async ctx => {
      const session = getSession(ctx.req, ctx.res)
      if (!session?.user) {
        return {
          redirect: {
            destination: `${loginUrl}?returnTo=${encodeURIComponent(returnTo || ctx.resolvedUrl)}`,
            permanent: false
          }
        }
      }

      let ret = {props: {}}
      if (getServerSideProps) {
        ret = await getServerSideProps(ctx)
      }

      return {...ret, props: {...ret.props, user: session.user}}
    }
  }
}```

Then, in `lib/auth0.js`, I’m exporting the following:

```js
export const withPageAuthRequired = (...args) => withPageAuthRequiredFactory()(...args)
```

And all is good.
But maybe, you should expose the `withPageAuthRequiredFactory`? Or something similar that allows to work with a custom auth0 instance with more ease?

**Comment by adamjmcgrath** [comment]
Hi @tusbar - you don't need the factory, you can just do

```js
export const getServerSideProps = (...args) => withPageAuthRequired({
  getServerSideProps: () => ({
    props: {foo: 'bar'}
  })
})(...args);
```

**Comment by tusbar** [comment]
@adamjmcgrath fair enough, but I believe that this complicates every page, and it differs from your docs and default implementation.

**Comment by francescovenica** [comment]
@adamjmcgrath I still have a small problem, I need to get the env async as I'm fetching them from a secret manager, how can I get the auth0 instance when using `withPageAuthRequired` if the function to get the instance is async?

**Comment by adamjmcgrath** [comment]
@francescovenica 

```js
export const getServerSideProps = async (ctx) => {
  const instance = await auth0();
  return instance.withPageAuthRequired()(ctx);
};
```

**Comment by adamjmcgrath** [comment]
@francescovenica 

```js
export const getServerSideProps = async (ctx) => {
  const instance = await auth0();
  return instance.withPageAuthRequired()(ctx);
};
```

**Comment by adamjmcgrath** [comment]
@francescovenica Closing this - feel free to ping me if you want me to reopen

**Comment by gabor-at-reed** [comment]
Hi @adamjmcgrath ,

Thanks for your help! Could you provide a solution for that scenario when we want to use the withPageAuthRequired() on CSR, but with an own instance? Like in @francescovenica 's case, we use secret manager to get the secrets for Auth0. 

I'm trying with a code like this:

```
import {auth0} from '../../../utils/auth0';

const AuthRequiredCSRExample = props => {
  // stuff...

  return (
    <>
      <p>more stuff...</p>
    </>
  );
};

const instance = await auth0();

export default instance.withPageAuthRequired(AuthRequiredCSRExample);

```

In the `next.config.js` I had to enable the top-level-await feature:

```
config.experiments = {
  ...config.experiments,
  topLevelAwait: true
};
```

But now I got an error message on the page which says:
![image](https://user-images.githubusercontent.com/1906302/140893645-23c6dbb1-a584-41b7-b461-b0402b44452f.png)

Any help would be appreciated!

**Comment by francescovenica** [comment]
I don't think you can use gcp-secret manager when CSR, it would be a security issue because you will expose gcp secret, in case of csr you probably need to use the spa library.....

**Comment by gabor-at-reed** [comment]
@francescovenica Yes, that's my fear as well, but I just tried to follow his guidance and the official Auth0 example from [here](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#protecting-a-client-side-rendered-csr-page).

It looks like if we have to get the secrets from somewhere (e.g. AWS secret manager), we lose the ability to use this CSR `withPageAuthRequired()` feature.

But current me, please if I'm wrong, @adamjmcgrath !

**Comment by adamjmcgrath** [comment]
Hey @gabor-at-reed - would you mind raising a separate issue for using CSR `withPageAuthRequired` with an own instance and I'll investigate

**Comment by etburke** [comment]
I've run into the same issue but am using the app router, so I don't think the `getServerSideProps` solution will work in my case. Can anyone recommend how I might approach this?
